первая попытка
urfu-2017/javascript-task-7 pull request #51
Opened 2017-11-30 11:52 UTC by AlexBarett

2017-11-30 11:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 15

2017-11-30 12:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 15

2017-11-30 12:30 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 13

2017-11-30 12:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 13

2017-11-30 12:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 13 из 13

2017-11-30 12:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-11-30 12:56 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-12-01 07:22 UTC, eugenest requested changes
фиксы

2017-12-01 07:22 UTC, eugenest commented on async.js
> +    let firsts = jobs.slice(0, parallelNum);
название переменной мало о чём говорит

2017-12-01 07:22 UTC, eugenest commented on async.js
> +
не нужно

2017-12-01 07:22 UTC, eugenest commented on async.js
> +        return new Promise (currentResolve => {
Promise (

пробел не нужен
я думал, линтер отсекает такие вещи

2017-12-01 07:22 UTC, eugenest commented on async.js
> +    function helper(answer, index, resolve) {
helper
плохое название
непонятно, что он делает

2017-12-06 08:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 15 из 15

2017-12-06 08:07 UTC, honest-hrundel commented
@eugenest обрати внимание: решено доп. задание

2017-12-06 11:49 UTC, closed without merging